// react/restaurant/src/Login.tsx
import axios from "axios"
import { useInput } from "./hooks"
import { useAtom } from "jotai"

import { isLoginAtom } from "./store"
import { Link, useNavigate } from "react-router-dom"

export default function Login() {
	let name = useInput('')
	let password = useInput('')
	let captcha = useInput('')
	let [isLogin, setIsLogin] = useAtom(isLoginAtom)
	let navigate = useNavigate()

	async function login() {
		try {
			let res = await axios.post('/api/login', {
				name: name.value,
				password: password.value,
				captcha: captcha.value
			})
			setIsLogin(true)
			navigate('/home')
		} catch (e: any) {
			if (e.isAxiosError) {
				alert('登录失败：' + e.response?.data.msg)
			} else {
				throw e
			}
		} 
	}
	if (isLogin) {
		return <div>已登录，去<Link to="/home">管理页面</Link></div>
	}
	return <div>
		<div className="h-12 m-2 flex items-center">
			<label className="flex gap-2"><span className="w-12 inline-block text-right">用户名</span> <input type='text' name='name' {...name}/></label>
		</div>
		<div className="h-12 m-2 flex items-center">
			<label className="flex gap-2"><span className="w-12 inline-block text-right">密码</span> <input type='password' name='password' {...password}/></label>
		</div>
		<div className="h-12 m-2 flex items-center">
			<label className="flex gap-2">
				<span className="w-12 inline-block text-right">验证码</span>
				<input type='text' name='captcha' {...captcha}/> 
			</label>
		</div>
		<div className="h-12 m-2 flex items-center">
			<label className="flex gap-2">
				<span className="w-12 inline-block text-right"></span>
				<img className="bg-white h-8" src="/api/captcha" alt="验证码" />
			</label>
		</div>
		<div className="h-12 m-2 flex items-center">
			<button className="ml-14" onClick={login}>登录</button>
		</div>
		
	</div>
}

// vue3/vote-vue3/src/views/Login.vue
<template>
	<div>
		<h1 class="p-4 text-xl">
			<RouterLink class="inline-flex gap-2 items-center" to="/">
				<el-icon class="relative top-px">
					<ArrowLeftBold />
				</el-icon>
				登录
			</RouterLink>
		</h1>
		<div class="px-4 h-12 flex items-center"><input placeholder="用户名" type="text" class="border text-xl focus:ring outline-none w-full" v-model="name"></div>
		<div class="px-4 h-12 flex items-center"><input placeholder="密码" type="password" class="border text-xl focus:ring outline-none w-full" v-model="password"></div>
		<button class="block bg-blue-500 text-white py-3  m-auto w-2/3 rounded mt-2" @click="login">登录</button>
	</div>
</template>

<script setup lang="ts">
import { useVoteStore } from '@/stores/vote'
import axios from 'axios'
import { ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'

	let name = ref('')
	let password = ref('')

	let route = useRoute()
	let router = useRouter()
	let voteStore = useVoteStore()
	let next = (route.query.next ?? '/') as string
	async function login() {
		try{
			let user = await axios.post('/account/login', {
				name: name.value,
				password: password.value,
			})

			voteStore.user = user.data.result
			router.replace(next)
		} catch(e) {
			alert('登录失败')
		}
	}
</script>
