// react/my-react-todo-app/src/TodoHeader.tsx
import { useAtom } from 'jotai'
import { isAllCompletedAtom, todosAtom } from './store'
import type { KeyboardEvent } from 'react'

export default function TodoHeader() {
	const [isAllCompleted] = useAtom(isAllCompletedAtom)
	const [, setTodos] = useAtom(todosAtom)

	function toggleAll() {
		setTodos(todos => {
			todos.forEach(it => {
				it.completed = !isAllCompleted
			})
		})
	}

	function addTodo(e: KeyboardEvent<HTMLInputElement>) {
		if (e.key == 'Enter') {
			const text = e.currentTarget.value
			if(text) {
				e.currentTarget.value = ''
				setTodos(todos => {
				todos.push({
					id: Math.random(),
					text,
					completed: false,
				})
			})
			}
		}
	}
	return <div>
		<input type='checkbox' checked={isAllCompleted} onChange={toggleAll}/>
		<input type='text' onKeyDown={addTodo}/>
	</div>
}

// vue3/vue-todo-pinia/src/TodoHeader.vue
<script setup>
	import { useTodos } from './store/todos.js';
	// 定义形参和事件
	var store = useTodos()
	// 业务函数
	
	
	function isAddTodo(event) {
		let text = event.target.value.trim()
		if (text) {
			store.addTodo(text)
			event.target.value = ''
		}
	}
</script>
<template>
	<h1>Todos</h1>
	<div>
		<input type="checkbox" :checked="store.isAllCompleted" @click="store.toggleAll">
	  <input type="text" placeholder="What needs to be done?" @keyup.enter="isAddTodo">
	</div>
</template>
